name: Deploy to Odoo Test

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy and restart Odoo Test
    runs-on: ubuntu-latest

    steps:
    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/staging.key
        chmod 600 ~/.ssh/staging.key
        cat >>~/.ssh/config <<END
        Host odoo
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/staging.key
          StrictHostKeyChecking no
        END
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}

      

    - name: Restart Odoo service
      run: |
        ssh -v odoo "sudo systemctl restart odoo-test"

    - name: Finish
      run: echo Finish

